// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.Server.Data;

namespace project.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220205002628_newdb")]
    partial class newdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            ConcurrencyStamp = "2e60a09c-9f70-43d2-94ff-0fc00073d455",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            ConcurrencyStamp = "ab21869d-5496-4409-a202-3c766d4ec46d",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("project.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "736d93c8-0b41-41d3-99dc-9ee5dc235c29",
                            Email = "admin@localhost.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEB55BrFFeLNG4lh04mqUAiD4RHY0PzqK6ktivgrFtOSQP9zgBqFN4+J8JkW0XKgpMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e5e9e67-99cd-44de-a484-85bf739d9d05",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("project.Shared.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departing")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoingToId")
                        .HasColumnType("int");

                    b.Property<int>("LeavingFromId")
                        .HasColumnType("int");

                    b.Property<int>("Passenger")
                        .HasColumnType("int");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Returning")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoingToId");

                    b.HasIndex("LeavingFromId");

                    b.HasIndex("PriceId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("project.Shared.Domain.BookingDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passenger")
                        .HasColumnType("int");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeOfVehicleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("luggage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.HasIndex("TypeOfVehicleId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("project.Shared.Domain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardType = "debit cards",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CardType = "credit cards",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("project.Shared.Domain.Flights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoingTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeavingFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 318, DateTimeKind.Local).AddTicks(439),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 318, DateTimeKind.Local).AddTicks(455),
                            GoingTo = "japan",
                            LeavingFrom = "Singapore",
                            Price = 780.0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 318, DateTimeKind.Local).AddTicks(463),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 318, DateTimeKind.Local).AddTicks(465),
                            GoingTo = "USA",
                            LeavingFrom = "Singapore",
                            Price = 1780.0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 318, DateTimeKind.Local).AddTicks(469),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 318, DateTimeKind.Local).AddTicks(470),
                            GoingTo = "china",
                            LeavingFrom = "Singapore",
                            Price = 580.0,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("project.Shared.Domain.TypeOfVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int>("Seat")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfVehicles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfVehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 311, DateTimeKind.Local).AddTicks(7347),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(5534),
                            Name = "Mitsubishi Mirage",
                            Price = 50.5,
                            Seat = 4,
                            TypeOfVehicles = "Economy Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7590),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7601),
                            Name = "Nissan Versa",
                            Price = 40.399999999999999,
                            Seat = 5,
                            TypeOfVehicles = "Compact Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7607),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7610),
                            Name = "Toyota Corolla",
                            Price = 45.130000000000003,
                            Seat = 5,
                            TypeOfVehicles = "MidSize Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7613),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7615),
                            Name = "Volkswagen Jetta",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Standard Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7621),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7623),
                            Name = "Chevy Malibu",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Full Size Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7626),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7628),
                            Name = "Ford Mustang Convertible",
                            Price = 30.300000000000001,
                            Seat = 4,
                            TypeOfVehicles = "Convertible Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7631),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7633),
                            Name = "Dodge Challenger",
                            Price = 30.300000000000001,
                            Seat = 4,
                            TypeOfVehicles = "Sporty Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7637),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7639),
                            Name = "INFINITI Q50",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Full Size Elite Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7643),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7645),
                            Name = " Audi A5 Sportback",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Full Size Elite Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7648),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7650),
                            Name = "BMW 228i Gran Coupe",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Standard Elite Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7654),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7656),
                            Name = "Tesla Model S",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Luxury Elite Electric Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7659),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7661),
                            Name = "Chevrolet Impala",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Premium Special Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7666),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7668),
                            Name = "BMW 5 Series ",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Premium Elite Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7671),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7673),
                            Name = "Nissan Maxima ",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Premium Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7676),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7678),
                            Name = "Chrysler 300",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7682),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7684),
                            Name = "Maserati Ghibli",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7687),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7689),
                            Name = "Mercedes AMG E53",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7692),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7695),
                            Name = "BMW 7 Series",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Large Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7698),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7700),
                            Name = "Mercedes Benz S Class",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Large Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7703),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7705),
                            Name = "Porsche Panamera",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Large Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7709),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7710),
                            Name = "Nissan Kicks",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Compact SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7714),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7716),
                            Name = "Nissan Rogue",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "MidSize SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7720),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7722),
                            Name = "Ford Edge ",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Standard SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7725),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7727),
                            Name = "Chevrolet Tahoe ",
                            Price = 30.300000000000001,
                            Seat = 7,
                            TypeOfVehicles = "Full Size SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7731),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7733),
                            Name = "Infiniti QX80",
                            Price = 30.300000000000001,
                            Seat = 7,
                            TypeOfVehicles = "Luxury SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7737),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7739),
                            Name = "Cadillac XT4",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Standard Elite SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7743),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7745),
                            Name = "Volkswagen Atlas",
                            Price = 30.300000000000001,
                            Seat = 7,
                            TypeOfVehicles = "Premium Crossover",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7748),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7750),
                            Name = "Mercedes Benz GLE",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Luxury Elite SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7754),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7756),
                            Name = "Chevy Suburban",
                            Price = 30.300000000000001,
                            Seat = 8,
                            TypeOfVehicles = "Premium SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7760),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7761),
                            Name = "BMW X3 ",
                            Price = 30.300000000000001,
                            Seat = 5,
                            TypeOfVehicles = "Premium Elite SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 31,
                            Capacity = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7765),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7767),
                            Name = "Chrysler Pacifica ",
                            Price = 30.300000000000001,
                            Seat = 7,
                            TypeOfVehicles = "7 Passenger Minivan",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7770),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7772),
                            Name = "Toyota Sienna",
                            Price = 30.300000000000001,
                            Seat = 8,
                            TypeOfVehicles = "8 Passenger Minivan",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 33,
                            Capacity = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7776),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7778),
                            Name = "Ford Transit Wagon",
                            Price = 30.300000000000001,
                            Seat = 12,
                            TypeOfVehicles = "12 Passenger Van",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 34,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7781),
                            DateUpdated = new DateTime(2022, 2, 5, 8, 26, 27, 314, DateTimeKind.Local).AddTicks(7783),
                            Name = "Ford Transit Wagon",
                            Price = 30.300000000000001,
                            Seat = 15,
                            TypeOfVehicles = "15 Passenger Van",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("project.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("project.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("project.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("project.Shared.Domain.Booking", b =>
                {
                    b.HasOne("project.Shared.Domain.Flights", "GoingTo")
                        .WithMany()
                        .HasForeignKey("GoingToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Shared.Domain.Flights", "LeavingFrom")
                        .WithMany()
                        .HasForeignKey("LeavingFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Shared.Domain.Flights", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoingTo");

                    b.Navigation("LeavingFrom");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("project.Shared.Domain.BookingDetails", b =>
                {
                    b.HasOne("project.Shared.Domain.TypeOfVehicle", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Shared.Domain.TypeOfVehicle", "TypeOfVehicle")
                        .WithMany()
                        .HasForeignKey("TypeOfVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Price");

                    b.Navigation("TypeOfVehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
