// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.Server.Data;

namespace project.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            ConcurrencyStamp = "21c7d87e-a5f8-4a96-adeb-63b6f72fa413",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            ConcurrencyStamp = "5c35f9b3-e39f-4795-bd0a-edcbfb7ec327",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("project.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7c6006a-5a6c-4eda-8c00-1dfe3466f027",
                            Email = "admin@localhost.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBh5idb1aKt5pgvbSVocoHS5s+9DkU6Nif3ibp5hQeR4F5AfHIMuAvTyVHtubKPfNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1ce5852-8a2c-4e0e-bbd4-e84f2786afe8",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("project.Shared.Domain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardType = "debit cards",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CardType = "credit cards",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("project.Shared.Domain.FlightBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departing")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightsId")
                        .HasColumnType("int");

                    b.Property<int>("Passenger")
                        .HasColumnType("int");

                    b.Property<DateTime>("Returning")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightsId");

                    b.ToTable("FlightBooking");
                });

            modelBuilder.Entity("project.Shared.Domain.Flights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoingTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 506, DateTimeKind.Local).AddTicks(1664),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 506, DateTimeKind.Local).AddTicks(1684),
                            GoingTo = "Japan",
                            Price = 780.0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 506, DateTimeKind.Local).AddTicks(1688),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 506, DateTimeKind.Local).AddTicks(1689),
                            GoingTo = "USA",
                            Price = 1780.0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 506, DateTimeKind.Local).AddTicks(1690),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 506, DateTimeKind.Local).AddTicks(1691),
                            GoingTo = "China",
                            Price = 580.0,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("project.Shared.Domain.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Seat")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfVehicles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 503, DateTimeKind.Local).AddTicks(5328),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(5744),
                            Name = "Mitsubishi Mirage",
                            Price = 40.0,
                            Seat = 4,
                            TypeOfVehicles = "Economy Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6609),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6615),
                            Name = "Nissan Versa",
                            Price = 60.0,
                            Seat = 5,
                            TypeOfVehicles = "Compact Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6617),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6618),
                            Name = "Toyota Corolla",
                            Price = 75.0,
                            Seat = 5,
                            TypeOfVehicles = "MidSize Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6619),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6620),
                            Name = "Volkswagen Jetta",
                            Price = 80.0,
                            Seat = 5,
                            TypeOfVehicles = "Standard Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6622),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6623),
                            Name = "Chevy Malibu",
                            Price = 85.0,
                            Seat = 5,
                            TypeOfVehicles = "Full Size Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6625),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6625),
                            Name = "Ford Mustang Convertible",
                            Price = 90.0,
                            Seat = 4,
                            TypeOfVehicles = "Convertible Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6627),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6628),
                            Name = "Dodge Challenger",
                            Price = 120.0,
                            Seat = 4,
                            TypeOfVehicles = "Sporty Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6630),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6630),
                            Name = "INFINITI Q50",
                            Price = 150.0,
                            Seat = 5,
                            TypeOfVehicles = "Full Size Elite Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6632),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6633),
                            Name = " Audi A5 Sportback",
                            Price = 180.0,
                            Seat = 5,
                            TypeOfVehicles = "Full Size Elite Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6635),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6636),
                            Name = "BMW 228i Gran Coupe",
                            Price = 180.0,
                            Seat = 5,
                            TypeOfVehicles = "Standard Elite Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6637),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6638),
                            Name = "Tesla Model S",
                            Price = 180.0,
                            Seat = 5,
                            TypeOfVehicles = "Luxury Elite Electric Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6640),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6640),
                            Name = "Chevrolet Impala",
                            Price = 180.0,
                            Seat = 5,
                            TypeOfVehicles = "Premium Special Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6642),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6643),
                            Name = "BMW 5 Series ",
                            Price = 180.0,
                            Seat = 5,
                            TypeOfVehicles = "Premium Elite Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6645),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6646),
                            Name = "Nissan Maxima ",
                            Price = 180.0,
                            Seat = 5,
                            TypeOfVehicles = "Premium Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6647),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6648),
                            Name = "Chrysler 300",
                            Price = 190.0,
                            Seat = 5,
                            TypeOfVehicles = "Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6650),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6650),
                            Name = "Maserati Ghibli",
                            Price = 190.0,
                            Seat = 5,
                            TypeOfVehicles = "Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6652),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6653),
                            Name = "Mercedes AMG E53",
                            Price = 200.0,
                            Seat = 5,
                            TypeOfVehicles = "Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6654),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6655),
                            Name = "BMW 7 Series",
                            Price = 250.0,
                            Seat = 5,
                            TypeOfVehicles = "Large Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6656),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6657),
                            Name = "Mercedes Benz S Class",
                            Price = 250.0,
                            Seat = 5,
                            TypeOfVehicles = "Large Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6659),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6660),
                            Name = "Porsche Panamera",
                            Price = 250.0,
                            Seat = 5,
                            TypeOfVehicles = "Large Executive Luxury Car",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6661),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6662),
                            Name = "Nissan Kicks",
                            Price = 120.0,
                            Seat = 5,
                            TypeOfVehicles = "Compact SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6663),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6664),
                            Name = "Nissan Rogue",
                            Price = 150.0,
                            Seat = 5,
                            TypeOfVehicles = "MidSize SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6666),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6667),
                            Name = "Ford Edge ",
                            Price = 180.0,
                            Seat = 5,
                            TypeOfVehicles = "Standard SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6669),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6670),
                            Name = "Chevrolet Tahoe ",
                            Price = 200.0,
                            Seat = 7,
                            TypeOfVehicles = "Full Size SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6671),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6672),
                            Name = "Infiniti QX80",
                            Price = 250.0,
                            Seat = 7,
                            TypeOfVehicles = "Luxury SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6674),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6674),
                            Name = "Cadillac XT4",
                            Price = 180.0,
                            Seat = 5,
                            TypeOfVehicles = "Standard Elite SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6676),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6677),
                            Name = "Volkswagen Atlas",
                            Price = 180.0,
                            Seat = 7,
                            TypeOfVehicles = "Premium Crossover",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6678),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6679),
                            Name = "Mercedes Benz GLE",
                            Price = 220.0,
                            Seat = 5,
                            TypeOfVehicles = "Luxury Elite SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6680),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6681),
                            Name = "Chevy Suburban",
                            Price = 220.0,
                            Seat = 8,
                            TypeOfVehicles = "Premium SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6683),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6684),
                            Name = "BMW X3 ",
                            Price = 250.0,
                            Seat = 5,
                            TypeOfVehicles = "Premium Elite SUV",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 31,
                            Capacity = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6685),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6686),
                            Name = "Chrysler Pacifica ",
                            Price = 200.0,
                            Seat = 7,
                            TypeOfVehicles = "7 Passenger Minivan",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6687),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6689),
                            Name = "Toyota Sienna",
                            Price = 220.0,
                            Seat = 8,
                            TypeOfVehicles = "8 Passenger Minivan",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 33,
                            Capacity = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6690),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6691),
                            Name = "Ford Transit Wagon",
                            Price = 230.0,
                            Seat = 12,
                            TypeOfVehicles = "12 Passenger Van",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 34,
                            Capacity = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6693),
                            DateUpdated = new DateTime(2022, 2, 7, 21, 35, 48, 504, DateTimeKind.Local).AddTicks(6694),
                            Name = "Ford Transit Wagon",
                            Price = 250.0,
                            Seat = 15,
                            TypeOfVehicles = "15 Passenger Van",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("project.Shared.Domain.VehicleBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passenger")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehiclesId")
                        .HasColumnType("int");

                    b.Property<int>("luggage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiclesId");

                    b.ToTable("VehicleBooking");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("project.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("project.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("project.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("project.Shared.Domain.FlightBooking", b =>
                {
                    b.HasOne("project.Shared.Domain.Flights", "Flights")
                        .WithMany()
                        .HasForeignKey("FlightsId");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("project.Shared.Domain.VehicleBooking", b =>
                {
                    b.HasOne("project.Shared.Domain.Vehicle", "Vehicles")
                        .WithMany()
                        .HasForeignKey("VehiclesId");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
